try {
    // 에러 객체를 생성한다고 에러가 발생하는 것은 아니다.
    new Error('something wrong');
  } catch (error) {
    console.log(error);
  }
  